const galleass = require("./galleass.js")
galleass.compile("Galleass")
galleass.compile("Land")
galleass.compile("Sea")
galleass.compile("Ships")
galleass.compile("Harbor")
galleass.compile("Fishmonger")
galleass.compile("Timber")
galleass.compile("Catfish")
galleass.compile("Pinner")
galleass.compile("Redbass")
galleass.compile("Snark")
galleass.compile("Dangler")
galleass.compile("Copper")
galleass.compile("Fillet")
