const galleass = require("./galleass.js")
galleass.compile("Galleass")
galleass.compile("Sea")
galleass.compile("Ships")
galleass.compile("Harbor")
galleass.compile("Timber")
galleass.compile("Catfish")
